site_name: NVIDIA TensorRT Developer Guide
theme: readthedocs
nav:
- 主页: 'index.md'
- 安装指南: 'installation_guide.md'
- 1. 简介: '01.introduction.md'
- 2. 功能特性: '02.tensorrt_capabilities.md'
- 3. C++ API: '03.the_c++_api.md'
- 4. Python API: '04.the_python_api.md'
- 5. 工作流程: '05.how_tensorrt_works.md'
- 6. 高级应用: '06.advanced_topics.md'
- 7. INT8 量化: '07.working_with_int8.md'
- 8. 动态shape: '08.working_with_dynamic_shapes.md'
- 9. 自定义网络层: '09.extending_tensorrt_with_custom_layers.md'
- 10. Loop结构: '10.working_with_loops.md'
- 11. 分支语句: '11.working_with_conditionals.md'
- 12. DLA: '12.working_with_dla.md'
- 13. 性能优化: '13.performance__best_practices.md'
- 14. 疑难解答: '14.troubleshooting.md'
- 15. 附录: 'a.appendix.md'
- 样例支持指南: 'sample_support_guide.md'
